Repository SamyArab/Condo-Management-Systems, pull requests merged in 2024-05, with the labels that each got.

#73 Dashboard/Profile for tenant
  CondoMAXium/components/layout/Footer.jsx
  CondoMAXium/components/layout/Header.jsx
  CondoMAXium/pages/dashboard/index.js
  CondoMAXium/pages/dashboardCMC/index.js
  CondoMAXium/pages/login/index.js
  CondoMAXium/pages/profile/index.js
  CondoMAXium/styles/profile.module.css
  CondoMAXium/test/profile.test.js
Labels: profile page, login page, CMC dashboard page, Testing, units dashboard page, owner dashboard page, High Priority

#72 User notification
  CondoMAXium/pages/dashboard/index.js
  CondoMAXium/pages/dashboardCMC/index.js
  CondoMAXium/pages/notifications-cmc/index.js
  CondoMAXium/pages/notifications/index.js
  CondoMAXium/test/notifications-cmc.test.js
  CondoMAXium/test/notifications.test.js
Labels: Testing, notification page

#71 Testing DashboardCMC
  CondoMAXium/pages/dashboardCMC/index.js
  CondoMAXium/test/dashboardCMC.test.js
Labels: CMC dashboard page, Testing, Medium Priority

#74 Fixed Deployment Issues
  CondoMAXium/.eslintrc.json
  CondoMAXium/package-lock.json
  CondoMAXium/package.json
  CondoMAXium/pages/dashboard/index.js
Labels: bug, High Priority, deployment

#69 Testing80 lache
  CondoMAXium/pages/add-property/index.js
  CondoMAXium/pages/add-request/index.js
  CondoMAXium/pages/requests-cmc/index.js
  CondoMAXium/pages/requests/index.js
  CondoMAXium/test/add-request.test.js
  CondoMAXium/test/addProperty.test.js
  CondoMAXium/test/dashboard.test.js
  CondoMAXium/test/login.test.js
  CondoMAXium/test/request-cmc.test.js
  CondoMAXium/test/request.test.js
Labels: Testing

#77 Deployment issues
  CondoMAXium/pages/requests-cmc/index.js
  CondoMAXium/pages/requests/index.js
Labels: bug, High Priority, deployment

#78 Mobile deployment on different operating systems
  CondoMAXium/next.config.js
  CondoMAXium/package.json
  CondoMAXium/pages/_document.js
  CondoMAXium/public/icon-192x192.png
  CondoMAXium/public/icon-256x256.png
  CondoMAXium/public/icon-384x384.png
  CondoMAXium/public/icon-512x512.png
  CondoMAXium/public/manifest.json
  CondoMAXium/public/sw.js
  CondoMAXium/public/sw.js.map
  CondoMAXium/public/workbox-e43f5367.js
  CondoMAXium/public/workbox-e43f5367.js.map
Labels: deployment
