Repository SamyArab/Condo-Management-Systems, pull requests merged in 2024-04, with the labels that each got.

#42 Backend facu anass
  CondoMAXium/pages/dashboard/index.js
  CondoMAXium/pages/dashboardCMC/index.js
  CondoMAXium/pages/login/index.js
Labels: login page, CMC dashboard page, database, owner dashboard page, High Priority

#43 Sign up using code
  CondoMAXium/pages/add-unit/index.js
  CondoMAXium/pages/profile/index.js
  CondoMAXium/pages/reset-password/index.js
  CondoMAXium/pages/signup/index.js
  CondoMAXium/pages/user-verification/index.js
  CondoMAXium/test/signup.test.js
Labels: bug, enhancement, sign up page

#49 Properties financial info
  CondoMAXium/pages/dashboardCMC/index.js
  CondoMAXium/pages/view-property/index.js
Labels: CMC dashboard page, finance

#55 Manage, add and edit employees
  CondoMAXium/pages/add-employee/index.js
  CondoMAXium/pages/edit-employee/index.js
  CondoMAXium/pages/manage-employees/index.js
Labels: enhancement

#57 Addition to testing of user-verification and reset-password files
  CondoMAXium/pages/reset-password/index.js
  CondoMAXium/pages/user-verification/index.js
  CondoMAXium/test/reset-password.test.js
  CondoMAXium/test/user-verification.test.js
Labels: Testing, registration-key

#62 improvement of testing coverage for units and finance
  CondoMAXium/pages/view-property/index.js
  CondoMAXium/test/edit-unit.test.js
  CondoMAXium/test/units.test.js
  CondoMAXium/test/view-property.test.js
  CondoMAXium/test/view-unit.test.js
Labels: Testing, units dashboard page, finance

#59 Deployment issue through UseRouter hook error
  CondoMAXium/pages/dashboardCMC/index.js
Labels: bug, Medium Priority, deployment

#65 Testing language addition
  CondoMAXium/.eslintrc.json
  CondoMAXium/pages/dashboardCMC/index.js
  CondoMAXium/pages/form-gym/index.js
  CondoMAXium/pages/form-rooftop-deck/index.js
  CondoMAXium/pages/form-spa/index.js
  CondoMAXium/pages/login/index.js
  CondoMAXium/pages/requests-cmc/index.js
Labels: enhancement, improvement, language

#66 Language translation of the website
  CondoMAXium/pages/login/index.js
  CondoMAXium/pages/profile/index.js
Labels: enhancement, improvement, language

#67 modified linting to allow script LANGUAGE
  CondoMAXium/.eslintrc.json
  CondoMAXium/pages/login/index.js
  CondoMAXium/pages/profile/index.js
Labels: enhancement, improvement, language

#68 all pages linked to translator
  CondoMAXium/pages/add-employee/index.js
  CondoMAXium/pages/add-property/index.js
  CondoMAXium/pages/add-request/index.js
  CondoMAXium/pages/add-unit/index.js
  CondoMAXium/pages/dashboard/index.js
  CondoMAXium/pages/dashboardCMC/index.js
  CondoMAXium/pages/edit-employee/index.js
  CondoMAXium/pages/edit-unit/index.js
  CondoMAXium/pages/form-gym/index.js
  CondoMAXium/pages/form-rooftop-deck/index.js
  CondoMAXium/pages/form-spa/index.js
  CondoMAXium/pages/maintenance-reservation/index.js
  CondoMAXium/pages/manage-employees/index.js
  CondoMAXium/pages/profile-form/index.js
  CondoMAXium/pages/requests-cmc/index.js
  CondoMAXium/pages/requests/index.js
  CondoMAXium/pages/reservation/index.js
  CondoMAXium/pages/reset-password/index.js
  CondoMAXium/pages/signup/index.js
  CondoMAXium/pages/units/index.js
  CondoMAXium/pages/user-verification/index.js
  CondoMAXium/pages/view-property/index.js
  CondoMAXium/pages/view-unit/index.js
Labels: enhancement, improvement, language
